title: Ainepadma
description: Personal site for notes and projects.
url: "https://ainepadma.github.io"
baseurl: ""
author: Ainepadma
email: Ainepadma24@gamil.com
github_username: ainepadma
avatar: https://github.com/ainepadma.png
